### PR TITLE
[enh] clicking on an action now saves the form

### PR DESCRIPTION
**Pull request by jibe-b**
pros:
- no longer loss of manually added data
- as anyhow email is sent to the author based on the current state of the form, nothing changed on email sending

solves https://github.com/OAButton/discussion/issues/785

### CODE REVIEW

**Comment by markmacgillivray** [comment]
If you trigger an adminsubmit, it will send a save request off to the backend. But if you then trigger the action, that will also send an action request to the backend WITHOUT waiting for the admin submission to complete. This would make it possible for the backend to be in the process of saving the request content when it then receives the request action, which itself can change request content and performs a save. I would be concerned that there is potential for one to overwrite the other here, or for the action to occur before the save completes, which means you will not be able to check to ensure that the content IS saved before the action executes.

If you really want to do this, I suggest you will have to alter the action function to actually call the adminsubmit function with an additional variable giving the name of the action to perform, and then the "success" function of adminsubmit should execute the action. Be careful not to cause an infinite loop doing this though.

**Comment by JosephMcArthur** [comment]
Thanks @markmacgillivray & @jibe-b. cc @natalianorori so she's got a heads up and is ready to test when this makes it onto develop.

**Comment by jibe-b** [comment]
Another set of requests have been sent empty unfortunately.

Temporarily, as only moderators see this form, a way to inform the moderator is:
page-shot-2017-7-19 open access button

That's commit https://github.com/OAButton/website/commit/e38f69477a2d2d63c914a57cee324fb14c58aa08 on the develop branch, hence visible on the dev website

**Comment by markmacgillivray** [comment]
This seems quite old now, closing as I assume it is no longer necessary. Can reopen another PR to the develop branch if required again.

**Pull request closed without merging**
